### ISSUE TITLE
Any awesome design books you recommend reading?

### ISSUE THREAD

**Issue by rbvea** [micjamking/ama#1]

**Comment by micjamking** [comment]
# My first question!!! :tada: :confetti_ball:

@rbvea First off, apologies for the delayed reply; I would have responded much sooner had I actually been watching the repository :confused: (not sure why I wasn't), but anyways...

Taking a quick glance underneath my work monitor, there's definitely a few of my favorites (and a couple of new ones) I'd highly recommend checking out:
![fullsizerender](https://cloud.githubusercontent.com/assets/651702/9676767/5d53c688-526c-11e5-8d40-6318095a65c5.jpg)

Top 5 design book recommendations...

#### 5. [Design is a Job](http://abookapart.com/products/design-is-a-job) by _Mike Montiero_
- Design is much more than just slinging pixels around in Photoshop or Illustrator (or more likely Sketch). Design is convincing clients your creative solutions are worth paying for. This book is all about the business of design for those who design for a living. From navigating client presentations to handling & responding to feedback, this book is a great short read, and told in a charming manner only [Mike Monteiro](https://twitter.com/monteiro) can pull off.

#### 4. [Web Form Design](http://www.lukew.com/resources/web_form_design.asp) by _Luke Wroblewski_
- This book is a great deep dive on a subject that's not a commonly discussed topic in web design, but critical for any and every web application that accepts information from users. What I like about this book, (and pretty much everything [Luke W.](http://www.lukew.com/ff/) writes, _[seriously](https://twitter.com/lukew)_) is that every design recommendation made is backed by tons of referenced research, including click testing and eyeball tracking studies. If you design web apps, this is a must read.

#### 3. [Designed for Use](https://pragprog.com/book/lmuse/designed-for-use) by _Lukas Mathis_
- A great comprehensive overview of the user experience process from initial user research, to design, to implementation. The perspective of the book is very hands on and targeted towards non-ux designers, so the subject matter is very approachable. This book covers the same topics as my [no. 1](#about-face-the-essentials-of-interaction-design) but not nearly as in-depth, so again, a good read for new and non-designers that want to understand the whole user experience design practice better.

#### 2. [Don't Make Me Think](http://www.sensible.com/dmmt.html) by _Steve Krug_
- I don't think this book needs much explanation, since it is widely considered a classic in web usability and interface design. It's a great introduction to usability for beginners, and a great practical refresher for seasoned designers. I keep a copy on my desk because I commonly refer to the examples in when explaining usability concepts to clients because of its simple explanations. Another must-read if you haven't already.

#### 1. [About Face: The Essentials of Interaction Design](http://www.wiley.com/WileyCDA/WileyTitle/productCd-1118766571.html) by _Alan Cooper_
- This is by far my favorite and most influential design book I've come across. @uxder recommended this to me when I first started out, and to this day I reference something in it on every project I work on. The first edition of this book came out in the early 90's and has somewhat revolutionized the industry of software design & development. Written by [Alan Cooper](https://twitter.com/MrAlanCooper) from [Cooper Design](http://www.cooper.com/about/), About Face is extremely comprehensive while also very practical with specific examples and methods for designing effective experiences.

#### Honorable Mentions
- **[Cadence & Slang](https://cadence.cc/)**: I just got this one but haven't dived in to it yet. The premise is great: simple & practical principles on interaction design. There's a [website](http://applied.cadence.cc/) with a few of the examples if you want to check it out before you read.
- **[Making Ideas Happen](http://99u.com/book/making-ideas-happen-2)**: This is generally a great read for anyone, and I've previously written a [blog post](http://uifuel.85pixels.com/book-review-making-ideas-happen/) about it, but it's simply one of my favorite books across the board, although not specific to design. It's about managing the natural, creative tendencies which cause ideas to fail and creating a plan to work with a bias towards action.
- **[The Entire A Book Apart Collection](http://abookapart.com/)**: _Design is a Job_ is part of this set, but generally you can't go wrong with any book from this collection. I've read books 1-8, and would also highly recommend [The Elements of Content Strategy](http://abookapart.com/products/the-elements-of-content-strategy), [Designing for Emotion](http://abookapart.com/products/designing-for-emotion), and [Mobile First](http://abookapart.com/products/mobile-first) (_Luke W. kills it again_).
